version: 0.0
os: linux 

hooks:
  ApplicationStop:
    - location: simple-python-app/scripts/stop_container.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: simple-python-app/scripts/start_container.sh
      timeout: 300
      runas: root
